INCLUDEPATH += $$PWD

SOURCES += \
    $$PWD/atomtreeviewchangeselectioncommand.cpp \
    $$PWD/atomtreeviewcopyselectiontonewmoviecommand.cpp \
    $$PWD/atomtreeviewfindprimitivecommand.cpp \
    $$PWD/atomtreeviewfindsymmetrycommand.cpp \
    $$PWD/atomtreeviewflattenhierarchycommand.cpp \
    $$PWD/atomtreeviewinvertselectioncommand.cpp \
    $$PWD/atomtreeviewmakesupercellcommand.cpp \
    $$PWD/atomtreeviewchangechargecommand.cpp \
    $$PWD/atomtreeviewchangedisplaynamecommand.cpp \
    $$PWD/atomtreeviewchangeelementcommand.cpp \
    $$PWD/atomtreeviewchangepositionxcommand.cpp \
    $$PWD/atomtreeviewchangepositionycommand.cpp \
    $$PWD/atomtreeviewchangepositionzcommand.cpp \
    $$PWD/atomtreeviewdeleteselectioncommand.cpp \
    $$PWD/atomtreeviewdropcopycommand.cpp \
    $$PWD/atomtreeviewdropmovecommand.cpp \
    $$PWD/atomtreeviewinsertatomcommand.cpp \
    $$PWD/atomtreeviewinsertatomgroupcommand.cpp \
    $$PWD/atomtreeviewmoveselectiontonewmoviecommand.cpp \
    $$PWD/atomtreeviewremovesymmetrycommand.cpp \
    $$PWD/atomtreeviewwrapatomstocellcommand.cpp \
    $$PWD/bondlistviewchangebondlengthcommand.cpp \
    $$PWD/bondlistviewchangeselectioncommand.cpp \
    $$PWD/bondlistviewdeleteselectioncommand.cpp \
    $$PWD/celltreewidgetappliedcellcontentshiftcommand.cpp \
    $$PWD/celltreewidgetchangespacegroupcommand.cpp \
    $$PWD/celltreewidgetchangestructurecommand.cpp \
    $$PWD/framelistviewchangedisplaynamecommand.cpp \
    $$PWD/framelistviewchangeselectioncommand.cpp \
    $$PWD/framelistviewdeleteselectioncommand.cpp \
    $$PWD/framelistviewdropcopycommand.cpp \
    $$PWD/framelistviewdropmovecommand.cpp \
    $$PWD/framelistviewinsertcommand.cpp \
    $$PWD/framelistviewpastecommand.cpp \
    $$PWD/projecttreeviewchangedisplaynamecommand.cpp \
    $$PWD/projecttreeviewchangeselectioncommand.cpp \
    $$PWD/projecttreeviewdeleteselectioncommand.cpp \
    $$PWD/projecttreeviewdropcopycommand.cpp \
    $$PWD/projecttreeviewdropmovecommand.cpp \
    $$PWD/projecttreeviewinsertprojectgroupcommand.cpp \
    $$PWD/projecttreeviewinsertprojectstructurecommand.cpp \
    $$PWD/projecttreeviewpasteprojectscommand.cpp \
    $$PWD/renderviewchangeselectioncommand.cpp \
    $$PWD/renderviewchangeselectionsubcommand.cpp \
    $$PWD/renderviewdeleteselectioncommand.cpp \
    $$PWD/renderviewdeleteselectionsubcommand.cpp \
    $$PWD/renderviewrotatepositionsbodyframecommand.cpp \
    $$PWD/renderviewrotatepositionsbodyframesubcommand.cpp \
    $$PWD/renderviewrotatepositionscartesiancommand.cpp \
    $$PWD/renderviewrotatepositionscartesiansubcommand.cpp \
    $$PWD/renderviewtranslatepositionsbodyframecommand.cpp \
    $$PWD/renderviewtranslatepositionsbodyframesubcommand.cpp \
    $$PWD/renderviewtranslatepositionscartesiancommand.cpp \
    $$PWD/renderviewtranslatepositionscartesiansubcommand.cpp \
    $$PWD/scenetreeviewchangemoviedisplaynamecommand.cpp \
    $$PWD/scenetreeviewchangescenedisplaynamecommand.cpp \
    $$PWD/scenetreeviewchangeselectioncommand.cpp \
    $$PWD/scenetreeviewdeletemoviesubcommand.cpp \
    $$PWD/scenetreeviewdeleteselectioncommand.cpp \
    $$PWD/scenetreeviewdraganddropinsertmoviesubcommand.cpp \
    $$PWD/scenetreeviewdraganddropmovemoviesubcommand.cpp \
    $$PWD/scenetreeviewdraganddropinsertscenesubcommand.cpp \
    $$PWD/scenetreeviewdropcopycommand.cpp \
    $$PWD/scenetreeviewdropmovecommand.cpp \
    $$PWD/scenetreeviewinsertmoviecommand.cpp \
    $$PWD/scenetreeviewinsertinitialscenecommand.cpp \
    $$PWD/scenetreeviewpasteprojectscommand.cpp

HEADERS += \
    $$PWD/atomtreeviewchangeselectioncommand.h \
    $$PWD/atomtreeviewcopyselectiontonewmoviecommand.h \
    $$PWD/atomtreeviewfindprimitivecommand.h \
    $$PWD/atomtreeviewfindsymmetrycommand.h \
    $$PWD/atomtreeviewflattenhierarchycommand.h \
    $$PWD/atomtreeviewinvertselectioncommand.h \
    $$PWD/atomtreeviewmakesupercellcommand.h \
    $$PWD/atomtreeviewchangechargecommand.h \
    $$PWD/atomtreeviewchangedisplaynamecommand.h \
    $$PWD/atomtreeviewchangeelementcommand.h \
    $$PWD/atomtreeviewchangepositionxcommand.h \
    $$PWD/atomtreeviewchangepositionycommand.h \
    $$PWD/atomtreeviewchangepositionzcommand.h \
    $$PWD/atomtreeviewdeleteselectioncommand.h \
    $$PWD/atomtreeviewdropcopycommand.h \
    $$PWD/atomtreeviewdropmovecommand.h \
    $$PWD/atomtreeviewinsertatomcommand.h \
    $$PWD/atomtreeviewinsertatomgroupcommand.h \
    $$PWD/atomtreeviewmoveselectiontonewmoviecommand.h \
    $$PWD/atomtreeviewremovesymmetrycommand.h \
    $$PWD/atomtreeviewwrapatomstocellcommand.h \
    $$PWD/bondlistviewchangebondlengthcommand.h \
    $$PWD/bondlistviewchangeselectioncommand.h \
    $$PWD/bondlistviewdeleteselectioncommand.h \
    $$PWD/celltreewidgetappliedcellcontentshiftcommand.h \
    $$PWD/celltreewidgetchangespacegroupcommand.h \
    $$PWD/celltreewidgetchangestructurecommand.h \
    $$PWD/framelistviewchangedisplaynamecommand.h \
    $$PWD/framelistviewchangeselectioncommand.h \
    $$PWD/framelistviewdeleteselectioncommand.h \
    $$PWD/framelistviewdropcopycommand.h \
    $$PWD/framelistviewdropmovecommand.h \
    $$PWD/framelistviewinsertcommand.h \
    $$PWD/framelistviewpastecommand.h \
    $$PWD/projecttreeviewchangedisplaynamecommand.h \
    $$PWD/projecttreeviewchangeselectioncommand.h \
    $$PWD/projecttreeviewdeleteselectioncommand.h \
    $$PWD/projecttreeviewdropcopycommand.h \
    $$PWD/projecttreeviewdropmovecommand.h \
    $$PWD/projecttreeviewinsertprojectgroupcommand.h \
    $$PWD/projecttreeviewinsertprojectstructurecommand.h \
    $$PWD/projecttreeviewpasteprojectscommand.h \
    $$PWD/renderviewchangeselectioncommand.h \
    $$PWD/renderviewchangeselectionsubcommand.h \
    $$PWD/renderviewdeleteselectioncommand.h \
    $$PWD/renderviewdeleteselectionsubcommand.h \
    $$PWD/renderviewrotatepositionsbodyframecommand.h \
    $$PWD/renderviewrotatepositionsbodyframesubcommand.h \
    $$PWD/renderviewrotatepositionscartesiancommand.h \
    $$PWD/renderviewrotatepositionscartesiansubcommand.h \
    $$PWD/renderviewtranslatepositionsbodyframecommand.h \
    $$PWD/renderviewtranslatepositionsbodyframesubcommand.h \
    $$PWD/renderviewtranslatepositionscartesiancommand.h \
    $$PWD/renderviewtranslatepositionscartesiansubcommand.h \
    $$PWD/scenetreeviewchangemoviedisplaynamecommand.h \
    $$PWD/scenetreeviewchangescenedisplaynamecommand.h \
    $$PWD/scenetreeviewchangeselectioncommand.h \
    $$PWD/scenetreeviewdeletemoviesubcommand.h \
    $$PWD/scenetreeviewdeleteselectioncommand.h  \
    $$PWD/scenetreeviewdraganddropinsertmoviesubcommand.h \
    $$PWD/scenetreeviewdraganddropmovemoviesubcommand.h \
    $$PWD/scenetreeviewdraganddropinsertscenesubcommand.h \
    $$PWD/scenetreeviewdropcopycommand.h \
    $$PWD/scenetreeviewdropmovecommand.h \
    $$PWD/scenetreeviewinsertmoviecommand.h \
    $$PWD/scenetreeviewinsertinitialscenecommand.h \
    $$PWD/scenetreeviewpasteprojectscommand.h
