.\" Man page for iraspa
.\" Contact d.dubbeldam@uva.nl
.TH iRASPA 1 "01 Oct 2020"
.SH NAME
iRASPA \- Molecular visualizer/editor
.SH SYNOPSIS
iRASPA is a molecular visualizer based on Qt and C++.
.SH DESCRIPTION
 iRASPA is a visualization package (with editing capabilities) aimed at
 material science. Examples of materials are metals, metal-oxides, ceramics,
 biomaterials, zeolites, clays, and metal-organic frameworks. iRASPA leverages
 the latest visualization technologies with high performance. It can
 handle large structures (hundreds of thousands of atoms), including ambient
 occlusion, with high frame rates.
 It is licensed under GPLv3. See COPYING file for more information.
.SH OPTIONS
No options for this man page
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below address.
.SH AUTHOR
David Dubbeldam (d.dubbeldam@uva.nl)
