/********************************************************************************************************************
    iRASPA: GPU-accelated visualisation software for materials scientists
    Copyright (c) 2016-2021 David Dubbeldam, Sofia Calero, Thijs J.H. Vlugt.
    D.Dubbeldam@uva.nl            https://www.uva.nl/en/profile/d/u/d.dubbeldam/d.dubbeldam.html
    S.Calero@tue.nl               https://www.tue.nl/en/research/researchers/sofia-calero/
    t.j.h.vlugt@tudelft.nl        http://homepage.tudelft.nl/v9k6y

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ********************************************************************************************************************/

#include "skelement.h"

SKElement::SKElement()
{

}

SKElement::SKElement(QString string, qint64 atomicNumber, qint64 group, qint64 period, QString name, double mass, double atomRadius, double covalentRadius, double singleBondCovalentRadius,
          double doubleBondCovalentRadius, double tripleBondCovalentRadius, double vDWRadius, std::vector<int> possibleOxidationStates):
          _chemicalSymbol(string), _atomicNumber(atomicNumber), _group(group), _period(period), _name(name), _mass(mass), _atomRadius(atomRadius), _covalentRadius(covalentRadius),
          _singleBondCovalentRadius(singleBondCovalentRadius), _doubleBondCovalentRadius(doubleBondCovalentRadius), _tripleBondCovalentRadius(tripleBondCovalentRadius),
          _VDWRadius(vDWRadius), _possibleOxidationStates(possibleOxidationStates)
{

}

// van der Waals: https://periodic.lanl.gov/1.shtml
// Van der Waals Radii of Elements, S. S. Batsanov
// https://physlab.lums.edu.pk/images/f/f6/Franck_ref2.pdf
std::vector<SKElement> PredefinedElements::predefinedElements =
{
    SKElement(QString(""), 0, 0, 0, QString(""), 0.0,0.0, 0.0, 0.0, 0.0, 0.0, 0.0,std::vector<int>{{}}),
    SKElement(QString("H"), 1, 1, 1, QString("Hydrogen"), 1.00794, 0.53, 0.32, 0.0, 0.0, 0.0, 1.2, std::vector<int>{-1,1}),
    SKElement(QString("He"), 2, 18, 1, QString("Helium"), 4.002602, 0.31, 0.28, 0.0, 0.0, 0.0, 1.4, std::vector<int>{0}),
    SKElement(QString("Li"), 3, 1, 2, QString("Lithium"), 6.9421, 1.67, 1.28, 0.0, 0.0, 0.0, 1.82, std::vector<int>{1}),
    SKElement(QString("Be"), 4, 2, 3, QString("Beryllium"), 9.012182, 1.12, 0.96, 0.0, 0.0, 0.85, 1.53, std::vector<int>{1,2}),
    SKElement(QString("B"), 5, 13, 2, QString("Boron"), 10.881, 0.90, 0.84, 0.0, 0.0, 0.73, 1.92, std::vector<int>{-5,-1,1,2,3}),
    SKElement(QString("C"), 6, 14, 2, QString("Carbon"), 12.0107, 0.67, 0.77, 0.0, 0.0, 0.69, 1.7, std::vector<int>{-4,-3,-2,-1,0,1,2,3,4}),
    SKElement(QString("N"), 7, 15, 2, QString("Nitrogen"), 14.0067, 0.56, 0.71, 0.0, 0.0, 0.54, 1.55, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(QString("O"), 8, 16, 2, QString("Oxygen"), 15.9994, 0.48, 0.66, 0.0, 0.0, 0.53, 1.52, std::vector<int>{-2,1,1,2}),
    SKElement(QString("F"), 9, 17, 2, QString("Fluorine"), 18.9984032, 0.42, 0.64, 0.0, 0.0, 0.53, 1.35, std::vector<int>{-1}),
    SKElement(QString("Ne"), 10, 18, 2, QString("Neon"), 20.1797, 0.38, 0.58, 0.0, 0.0, 0.0, 1.54, std::vector<int>{0}),
    SKElement(QString("Na"), 11, 1, 3, QString("Sodium"), 22.98976928, 1.86, 1.66, 0.0, 0.0, 0.0, 2.27, std::vector<int>{-1,1}),
    SKElement(QString("Mg"), 12, 2, 3, QString("Magnesium"), 24.305, 1.60, 1.41, 0.0, 0.0, 1.27, 1.73, std::vector<int>{1,2}),
    SKElement(QString("Al"), 13, 13, 3, QString("Aluminum"), 26.9815386, 1.43, 1.21, 0.0, 0.0, 1.11, 1.84, std::vector<int>{-2,-1,1,2,3}),
    SKElement(QString("Si"), 14, 14, 3, QString("Silicon"), 28.0855, 1.11, 1.11, 0.0, 0.0, 1.02, 2.1, std::vector<int>{-4,-3,-2,-1,1,2,3,4}),
    SKElement(QString("P"), 15, 15, 3, QString("Phosphorus"), 30.973762, 0.98, 1.07, 0.0, 0.0, 0.94, 1.8, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(QString("S"), 16, 16, 3, QString("Sulfur"), 32.065, 0.88, 1.05, 0.0, 0.0, 0.95, 1.8, std::vector<int>{-2,-1,1,2,3,4,5,6}),
    SKElement(QString("Cl") ,17, 17, 3, QString("Chlorine"), 35.453, 0.79, 1.02, 0.0, 0.0, 0.93, 1.75, std::vector<int>{-1,1,2,3,4,5,6,7}),
    SKElement(QString("Ar") ,18, 18, 3, QString("Argon"), 39.948, 0.71, 1.06, 0.0, 0.0, 0.96, 1.88, std::vector<int>{0}),
    SKElement(QString("K") ,19, 1, 4, QString("Potassium"), 39.0983, 2.27, 2.03, 0.0, 0.0, 0.0, 2.75, std::vector<int>{-1,1}),
    SKElement(QString("Ca"), 20, 2, 4, QString("Calcium"), 40.078, 1.97, 1.76, 0.0, 0.0, 1.33, 2.31, std::vector<int>{1,2}),
    SKElement(QString("Sc"), 21, 3, 4, QString("Scandium"), 44.955912, 1.62, 1.7, 0.0, 0.0, 1.14, 2.11, std::vector<int>{1,2,3}),
    SKElement(QString("Ti"), 22, 4, 4, QString("Titanium"), 47.867, 1.47, 1.6, 0.0, 0.0, 1.08, 1.87, std::vector<int>{-2,-1,1,2,3,4}),
    SKElement(QString("V"), 23, 5, 4, QString("Vanadium"), 50.9415, 1.34, 1.53, 0.0, 0.0, 1.06, 1.79, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(QString("Cr"), 24, 6, 4, QString("Chromium"), 51.9961, 1.28, 1.39, 0.0, 0.0, 1.03, 1.89, std::vector<int>{-4,-2,-1,1,2,3,4,5,6}),
    SKElement(QString("Mn"), 25, 7, 4, QString("Manganese"), 54.939045, 1.27, 1.39, 0.0, 0.0, 1.03, 1.97, std::vector<int>{-3,-2,1,1,2,3,4,5,6,7}),
    SKElement(QString("Fe"), 26, 8, 4, QString("Iron"), 55.845, 1.26, 1.32, 0.0, 0.0, 1.02, 1.94, std::vector<int>{-4,-2,-1,1,2,3,4,5,6,7}),
    SKElement(QString("Co"), 27, 9, 4, QString("Cobalt"), 58.933195, 1.25, 1.26, 0.0, 0.0, 0.96, 1.92, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(QString("Ni"), 28, 10, 4, QString("Nickel"), 58.6934 , 1.24, 1.24, 0.0, 0.0, 1.01, 1.63, std::vector<int>{-2,-1,1,2,3,4}),
    SKElement(QString("Cu"), 29, 11, 4, QString("Copper"), 63.546,1.28, 1.32, 0.0, 0.0, 1.2, 1.4, std::vector<int>{-2,1,2,3,4}),
    SKElement(QString("Zn"), 30, 12, 4, QString("Zinc"), 65.38, 1.34, 1.22, 0.0, 0.0, 0.0, 1.39, std::vector<int>{-2,0,1,2}),
    SKElement(QString("Ga"), 31, 13, 4, QString("Gallium"), 69.723, 1.35, 1.22, 0.0, 0.0, 1.21, 1.87, std::vector<int>{-5,-4,-2,-1,1,2,3}),
    SKElement(QString("Ge"), 32, 14, 4, QString("Germanium"), 72.64, 1.22, 1.22, 0.0, 0.0, 1.14, 2.11, std::vector<int>{-4,-3,-2,-1,0,1,2,3,4}),
    SKElement(QString("As"), 33, 15, 4, QString("Arsenic"), 74.9216, 1.19, 1.19, 0.0, 0.0, 1.06, 1.85, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(QString("Se"), 34, 16, 3, QString("Selenium"), 78.96, 1.20, 1.2, 0.0, 0.0, 1.07, 1.9, std::vector<int>{-2,-1,1,2,3,4,5,6}),
    SKElement(QString("Br"), 35, 17, 4, QString("Bromine"), 79.904, 1.20, 1.2, 0.0, 0.0, 1.1, 1.83, std::vector<int>{-1,1,3,4,5,7}),
    SKElement(QString("Kr"), 36, 18, 4, QString("Krypton"), 83.798, 0.88, 1.16, 0.0, 0.0, 1.08, 2.02, std::vector<int>{0,1,2}),
    SKElement(QString("Rb"), 37, 1, 5, QString("Rubidium"), 85.4678, 2.48, 2.2, 0.0, 0.0, 0.0, 3.03, std::vector<int>{-1,1}),
    SKElement(QString("Sr"), 38, 2, 5, QString("Strontium"), 87.62, 2.15, 1.95, 0.0, 0.0, 1.39, 2.49, std::vector<int>{1,2}),
    SKElement(QString("Y"), 39, 3, 5, QString("Yttrium"), 88.90585, 1.80, 1.9, 0.0, 0.0, 1.24, 2.19, std::vector<int>{1,2,3}),
    SKElement(QString("Zr"), 40, 4, 5, QString("Zirconium"), 91.224, 1.60, 1.75, 0.0, 0.0, 1.21, 1.86, std::vector<int>{-2,1,2,3,4}),
    SKElement(QString("Nb"), 41, 5, 5, QString("Niobium"), 92.90638, 1.46, 1.64, 0.0, 0.0, 1.16, 2.07, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(QString("Mo"), 42, 6, 5, QString("Molybdenum"), 95.96, 1.39, 1.54, 0.0, 0.0, 1.13, 2.09, std::vector<int>{-4,-2,-1,1,2,3,4,5,6}),
    SKElement(QString("Tc"), 43, 7, 5, QString("Technetium"), 98, 1.36, 1.47, 0.0, 0.0, 1.10, 2.09, std::vector<int>{-3,-1,1,2,3,4,5,6,7}),
    SKElement(QString("Ru"), 44, 8, 5, QString("Ruthenium"), 101.07, 1.34, 1.46, 0.0, 0.0, 1.03, 2.07, std::vector<int>{-4,-2,1,2,3,4,5,6,7,8}),
    SKElement(QString("Rh"), 45, 9, 5, QString("Rhodium"), 102.59055, 1.34, 1.42, 0.0, 0.0, 1.06, 1.95, std::vector<int>{-3,-1,1,2,3,4,5,6}),
    SKElement(QString("Pd"), 46, 10, 5, QString("Palladium"), 106.42, 1.37, 1.39, 0.0, 0.0, 1.12, 2.02, std::vector<int>{0,1,2,3,4}),
    SKElement(QString("Ag"), 47, 11, 5, QString("Silver"), 107.8682, 1.44, 1.45, 0.0, 0.0, 1.37, 1.72, std::vector<int>{-2,-1,1,2,3}),
    SKElement(QString("Cd"), 48, 12, 5, QString("Cadmium"), 112.411, 1.51, 1.44, 0.0, 0.0, 0.0, 1.58, std::vector<int>{-2,1,2}),
    SKElement(QString("In"), 49, 13, 5, QString("Indium"), 114.818, 1.67, 1.42, 0.0, 0.0, 1.46, 1.93, std::vector<int>{-5,-2,-1,1,2,3}),
    SKElement(QString("Sn"), 50, 14, 5, QString("Tin"), 118.71, 1.40, 1.39, 0.0, 0.0, 1.32, 2.17, std::vector<int>{-4,-3,-2,-1,1,2,3,4}),
    SKElement(QString("Sb"), 51, 15, 5, QString("Antimony"), 121.76, 1.40, 1.39, 0.0, 0.0, 1.27, 2.06, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(QString("Te"), 52, 16, 5, QString("Tellurium"), 127.6, 1.40, 1.38, 0.0, 0.0, 1.21, 2.06, std::vector<int>{-2,-1,1,2,3,4,5,6}),
    SKElement(QString("I"), 53, 17, 5, QString("Iodine"), 126.90447, 1.40, 1.39, 0.0, 0.0, 1.25, 1.98, std::vector<int>{-1,1,3,4,5,6,7}),
    SKElement(QString("Xe"), 54, 18, 5, QString("Xenon"), 131.293, 1.08, 1.4, 0.0, 0.0, 1.22, 2.16, std::vector<int>{0,1,2,4,6,8}),
    SKElement(QString("Cs"), 55, 1, 6, QString("Cesium"), 132.9054519, 2.65, 2.44, 0.0, 0.0, 0.0, 3.43, std::vector<int>{-1,1}),
    SKElement(QString("Ba"), 56, 2, 6, QString("Barium"), 137.327, 2.22, 2.15, 0.0, 0.0, 1.49, 2.68, std::vector<int>{1,2}),
    SKElement(QString("La"), 57, -1, 6, QString("Lanthanum"), 138.90547, 1.87, 2.07, 0.0, 0.0, 1.39, 2.40, std::vector<int>{1,2,3}),
    SKElement(QString("Ce"), 58, -1, 6, QString("Cerium"), 140.116, 1.818, 2.04, 0.0, 0.0, 1.31, 2.35, std::vector<int>{1,2,3,4}),
    SKElement(QString("Pr"), 59, -1, 6, QString("Praseodymium"), 140.90765, 1.82, 2.03, 0.0, 0.0, 1.28, 2.39, std::vector<int>{2,3,4,5}),
    SKElement(QString("Nd"), 60, -1, 6, QString("Neodymium"), 144.242, 1.81, 2.01, 0.0, 0.0, 0.0, 2.29, std::vector<int>{2,3,4}),
    SKElement(QString("Pm"), 61, -1, 6, QString("Promethium"), 145, 1.83, 1.99, 0.0, 0.0, 0.0, 2.36, std::vector<int>{2,3}),
    SKElement(QString("Sm"), 62, -1, 6, QString("Samarium"), 150.36, 1.80, 1.98, 0.0, 0.0, 0.0, 2.29, std::vector<int>{1,2,3,4}),
    SKElement(QString("Eu"), 63, -1, 6, QString("Europium"), 151.964, 1.80, 1.98, 0.0, 0.0, 0.0, 2.33, std::vector<int>{1,2,3}),
    SKElement(QString("Gd"), 64, -1, 6, QString("Gadolinium"), 157.25, 1.80, 1.96, 0.0, 0.0, 1.32, 2.37, std::vector<int>{1,2,3}),
    SKElement(QString("Tb"), 65, -1, 6, QString("Terbium"), 158.92535, 1.77, 1.94, 0.0, 0.0, 0.0, 2.21, std::vector<int>{1,2,3,4}),
    SKElement(QString("Dy"), 66, -1, 6, QString("Dysprosium"), 162.5, 1.78, 1.92, 0.0, 0.0, 0.0, 2.29, std::vector<int>{1,2,3,4}),
    SKElement(QString("Ho"), 67, -1, 6, QString("Holmium"), 164.93032, 1.76, 1.92, 0.0, 0.0, 0.0, 2.16, std::vector<int>{1,2,3}),
    SKElement(QString("Er"), 68, -1, 6, QString("Erbium"), 167.259, 1.76, 1.89, 0.0, 0.0, 0.0, 2.35, std::vector<int>{1,2,3}),
    SKElement(QString("Tm"), 69, -1, 6, QString("Thulium"), 168.93421, 1.76, 1.9, 0.0, 0.0, 0.0, 2.27, std::vector<int>{2,3}),
    SKElement(QString("Yb"), 70, -1, 6, QString("Ytterbium"), 173.054, 1.76, 1.87, 0.0, 0.0, 0.0, 2.42, std::vector<int>{1,2,3}),
    SKElement(QString("Lu"), 71, 3, 6, QString("Lutetium"), 174.9668, 1.74, 1.87, 0.0, 0.0, 1.31, 2.21, std::vector<int>{1,2,3}),
    SKElement(QString("Hf"), 72, 4, 6, QString("Hafnium"), 178.49, 1.59, 1.75, 0.0, 0.0, 1.22, 2.12, std::vector<int>{-2,1,2,3,4}),
    SKElement(QString("Ta"), 73, 5, 6, QString("Tantalum"), 180.94788, 1.46, 1.7, 0.0, 0.0, 1.19, 2.17, std::vector<int>{-3,-1,1,2,3,4,5}),
    SKElement(QString("W"), 74, 6, 6, QString("Tungsten"), 183.84, 1.39, 1.62, 0.0, 0.0, 1.15, 2.10, std::vector<int>{-4,-2,-1,0,1,2,3,4,5,6}),
    SKElement(QString("Re"), 75, 7, 6, QString("Rhenium"), 186.207, 1.37, 1.51, 0.0, 0.0, 1.1, 2.17, std::vector<int>{-3,-1,0,1,2,3,4,5,6,7}),
    SKElement(QString("Os"), 76, 8, 6, QString("Osmium"), 190.23, 1.35, 1.44, 0.0, 0.0, 1.09, 2.16, std::vector<int>{-4,-2,0,1,2,3,4,5,6,7,8}),
    SKElement(QString("Ir"), 77, 9, 6, QString("Iridium"), 192.217, 1.36, 1.41, 0.0, 0.0, 1.07, 2.02, std::vector<int>{-3,-1,0,1,2,3,4,5,6,7,8,9}),
    SKElement(QString("Pt"), 78, 10, 6, QString("Platinum"), 195.084, 1.39, 1.36, 0.0, 0.0, 1.1, 2.09, std::vector<int>{-3,-2,-1,2,3,4,5,6}),
    SKElement(QString("Au"), 79, 11, 6, QString("Gold"), 196.966569, 1.44, 1.36, 0.0, 0.0, 1.23, 1.66, std::vector<int>{-3,-2,-1,1,2,3,5}),
    SKElement(QString("Hg"), 80, 12, 6, QString("Mercury"), 200.59, 1.51, 1.32, 0.0, 0.0, 1.55, 2.09, std::vector<int>{-2,1,2}),
    SKElement(QString("Tl"), 81, 13, 6, QString("Thallium"), 204.3833, 1.70, 1.45, 0.0, 0.0, 0.15, 1.96, std::vector<int>{-5,-2,-1,1,2,3}),
    SKElement(QString("Pb"), 82, 14, 6, QString("Lead"), 207.2, 1.75, 1.46, 0.0, 0.0, 1.37, 2.02, std::vector<int>{-4,-2,-1,2,3,4}),
    SKElement(QString("Bi"), 83, 15, 6, QString("Bismuth"), 208.9804, 1.56, 1.48, 0.0, 0.0, 1.35, 2.07, std::vector<int>{-3,-2,-1,1,2,3,4,5}),
    SKElement(QString("Po"), 84, 16, 6, QString("Polonium"), 210, 1.68, 1.4, 0.0, 0.0, 1.29, 1.97, std::vector<int>{-2,2,4,5,6}),
    SKElement(QString("At"), 85, 17, 6, QString("Astatine"), 210.8, 0.0, 1.5, 0.0, 0.0, 1.38, 2.02, std::vector<int>{-1,1,3,5,7}),
    SKElement(QString("Rn"), 86, 18, 6, QString("Radon"), 222, 1.2, 1.5, 0.0, 0.0, 1.33, 2.20, std::vector<int>{0,2,6}),
    SKElement(QString("Fr"), 87, 1, 7, QString("Francium"), 223, 0.0, 2.6, 0.0, 0.0, 0.0, 3.48, std::vector<int>{1}),
    SKElement(QString("Ra"), 88, 2, 7, QString("Radium"), 226, 0.0, 2.21, 0.0, 0.0, 1.59, 2.83, std::vector<int>{2}),
    SKElement(QString("Ac"), 89, -1, 7, QString("Actinium"), 227, 0.0, 2.15, 0.0, 0.0, 1.4, 2.60, std::vector<int>{2,3}),
    SKElement(QString("Th"), 90, -1, 7, QString("Thorium"), 232.03806, 1.798, 2.06, 0.0, 0.0, 1.36, 2.37, std::vector<int>{1,2,3,4}),
    SKElement(QString("Pa"), 91, -1, 7, QString("Protactinium"), 231.03588, 1.63, 2.0, 0.0, 0.0, 1.29, 2.43, std::vector<int>{2,3,4,5}),
    SKElement(QString("U"), 92, -1, 7, QString("Uranium"), 238.02891, 1.56, 1.96, 0.0, 0.0, 1.18, 2.40, std::vector<int>{1,2,3,4,5,6}),
    SKElement(QString("Np"), 93, -1, 7, QString("Neptunium"), 237, 1.55, 1.9, 0.0, 0.0, 1.16, 2.21, std::vector<int>{2,3,4,5,6,7}),
    SKElement(QString("Pu"), 94, -1, 7, QString("Plutonium"), 244, 1.59, 1.87, 0.0, 0.0, 0.0, 2.43, std::vector<int>{1,2,3,4,5,6,7,8}),
    SKElement(QString("Am"), 95, -1, 7, QString("Americium"), 243, 1.73, 1.8, 0.0, 0.0, 0.0, 2.44, std::vector<int>{2,3,4,5,6,7,8}),
    SKElement(QString("Cm"), 96, -1, 7, QString("Curium"), 247, 1.74, 1.69, 0.0, 0.0, 0.0, 2.45, std::vector<int>{2,3,4,6}),
    SKElement(QString("Bk"), 97, -1, 7, QString("Berkelium"), 247, 1.7, 0.0, 0.0, 0.0, 0.0, 2.44, std::vector<int>{2,3,4}),
    SKElement(QString("Cf"), 98, -1, 7, QString("Californium"), 251, 0.0, 0.0, 0.0, 0.0, 0.0, 2.45, std::vector<int>{2,3,4}),
    SKElement(QString("Es"), 99, -1, 7, QString("Einsteinium"), 252, 0.0, 0.0, 0.0, 0.0, 0.0, 2.45, std::vector<int>{2,3,4}),
    SKElement(QString("Fm"), 100, -1, 7, QString("Fermium"), 257, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, std::vector<int>{2,3}),
    SKElement(QString("Md"), 101, -1, 7, QString("Mendelevium"), 258, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, std::vector<int>{2,3}),
    SKElement(QString("No"), 102, -1, 7, QString("Nobelium"), 259, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, std::vector<int>{2,3}),
    SKElement(QString("Lr"), 103, 3, 7, QString("Lawrencium"), 262, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, std::vector<int>{3}),
    SKElement(QString("Rf"), 104, 4, 7, QString("Rutherfordium"), 261, 0.0, 0.0, 0.0, 0.0, 1.31, 0.0, std::vector<int>{2,3,4}),
    SKElement(QString("Db"), 105, 5, 7, QString("Dubnium"), 268, 1.39, 1.49, 0.0, 0.0, 1.26, 0.0, std::vector<int>{3,4,5}),
    SKElement(QString("Sg"), 106, 6, 7, QString("Seaborgium"), 269, 1.32, 1.43, 0.0, 0.0, 1.21, 0.0, std::vector<int>{3,4,5,6}),
    SKElement(QString("Bh"), 107, 7, 7, QString("Bohrium"), 270, 1.28, 1.41, 0.0, 0.0, 1.19, 0.0, std::vector<int>{3,4,5,7}),
    SKElement(QString("Hs"), 108, 8, 7, QString("Hassium"), 269, 1.26, 1.34, 0.0, 0.0, 1.18, 0.0, std::vector<int>{2,3,4,5,6,8}),
    SKElement(QString("Mt"), 109, 9, 7, QString("Meitnerium"), 278, 1.28, 1.29, 0.0, 0.0, 1.13, 0.0, std::vector<int>{1,3,4,6,8,9}),
    SKElement(QString("Ds"), 110, 10, 7, QString("Darmstadtium"), 281, 1.32, 1.28, 0.0, 0.0, 1.12, 0.0, std::vector<int>{0,2,4,6,8}),
    SKElement(QString("Rg"), 111, 11, 7, QString("Roentgenium"), 281, 1.38, 1.21, 0.0, 0.0, 1.18, 0.0, std::vector<int>{-1,1,3,5}),
    SKElement(QString("Cn"), 112, 12, 7, QString("Copernicium"), 285, 1.47, 1.22, 0.0, 0.0, 1.30, 0.0, std::vector<int>{0,1,2}),
    SKElement(QString("Nh"), 113, 13, 7, QString("Nihonium"), 286, 1.70, 1.76, 0.0, 0.0, 0.0, 0.0, std::vector<int>{-1,1,3,5}),
    SKElement(QString("Fl"), 114, 14, 7, QString("Flerovium"), 289, 1.80, 1.74, 0.0, 0.0, 0.0, 0.0, std::vector<int>{0,1,2,4,6}),
    SKElement(QString("Mc"), 115, 15, 7, QString("Moscovium"), 288, 1.87, 1.57, 0.0, 0.0, 0.0, 0.0, std::vector<int>{1,3}),
    SKElement(QString("Lv"), 116, 16, 7, QString("Livermorium"), 293, 1.83, 1.64, 0.0, 0.0, 0.0, 0.0, std::vector<int>{-2,2,4}),
    SKElement(QString("Ts"), 117, 17, 7, QString("Tennessine"), 294, 1.38, 1.56, 0.0, 0.0, 0.0, 0.0, std::vector<int>{-1,1,3,5}),
    SKElement(QString("Og"), 118, 18, 7, QString("Oganesson"), 294, 1.52, 1.57, 0.0, 0.0, 0.0, 0.0, std::vector<int>{-1,0,1,2,4,6})
};

std::map<QString, int> PredefinedElements::atomicNumberData =
{
    {QString("H"), 1}, {QString("He"), 2}, {QString("Li"), 3}, {QString("Be"), 4}, {QString("B"), 5}, {QString("C"), 6}, {QString("N"), 7}, {QString("O"), 8}, {QString("F"), 9},
    {QString("Ne"), 10}, {QString("Na"), 11}, {QString("Mg"), 12}, {QString("Al"), 13}, {QString("Si"), 14}, {QString("P"), 15}, {QString("S"), 16,}, {QString("Cl"), 17}, {QString("Ar"), 18}, {QString("K"), 19},
    {QString("Ca"), 20}, {QString("Sc"), 21}, {QString("Ti"), 22}, {QString("V"), 23}, {QString("Cr"), 24}, {QString("Mn"), 25}, {QString("Fe"), 26}, {QString("Co"), 27}, {QString("Ni"), 28}, {QString("Cu"), 29},
    {QString("Zn"), 30}, {QString("Ga"), 31}, {QString("Ge"), 32}, {QString("As"), 33}, {QString("Se"), 34,}, {QString("Br"), 35}, {QString("Kr"), 36}, {QString("Rb"), 37}, {QString("Sr"), 38}, {QString("Y"), 39},
    {QString("Zr"), 40}, {QString("Nb"), 41}, {QString("Mo"), 42}, {QString("Tc"), 43}, {QString("Ru"), 44}, {QString("Rh"), 45}, {QString("Pd"), 46}, {QString("Ag"), 47}, {QString("Cd"), 48}, {QString("In"), 49},
    {QString("Sn"), 50}, {QString("Sb"), 51}, {QString("Te"), 52}, {QString("I"), 53}, {QString("Xe"), 54}, {QString("Cs"), 55}, {QString("Ba"), 56}, {QString("La"), 57}, {QString("Ce"), 58}, {QString("Pr"), 59},
    {QString("Nd"), 60}, {QString("Pm"), 61}, {QString("Sm"), 62}, {QString("Eu"), 63}, {QString("Gd"), 64}, {QString("Tb"), 65}, {QString("Dy"), 66}, {QString("Ho"), 67}, {QString("Er"), 68}, {QString("Tm"), 69},
    {QString("Yb"), 70}, {QString("Lu"), 71}, {QString("Hf"), 72}, {QString("Ta"), 73}, {QString("W"), 74}, {QString("Re"), 75}, {QString("Os"), 76}, {QString("Ir"), 77}, {QString("Pt"), 78}, {QString("Au"), 79},
    {QString("Hg"), 80}, {QString("Tl"), 81}, {QString("Pb"), 82}, {QString("Bi"), 83}, {QString("Po"), 84}, {QString("At"), 85}, {QString("Rn"), 86}, {QString("Fr"), 87}, {QString("Ra"), 88}, {QString("Ac"), 89},
    {QString("Th"), 90}, {QString("Pa"), 91}, {QString("U"), 92}, {QString("Np"), 93}, {QString("Pu"), 94}, {QString("Am"), 95}, {QString("Cm"), 96}, {QString("Bk"), 97}, {QString("Cf"), 98}, {QString("Es"), 99},
    {QString("Fm"), 100}, {QString("Md"), 101}, {QString("No"), 102}, {QString("Lr"), 103}, {QString("Rf"), 104}, {QString("Db"), 105}, {QString("Sg"), 106}, {QString("Bh"), 107}, {QString("Hs"), 108}, {QString("Mt"), 109},
    {QString("Ds"), 110}, {QString("Rg"), 111}, {QString("Cn"), 112}, {QString("Nh"), 113}, {QString("Fl("), 114}, {QString("Mc"), 115}, {QString("Lv"), 116}, {QString("Ts"), 117}, {QString("Og"), 118}
};

std::set<QString> PredefinedElements::residueDefinitions =
{
  QString("ALA"),
  QString("ARG"),
  QString("ASN"),
  QString("ASP"),
  QString("CYS"),
  QString("GLN"),
  QString("GLU"),
  QString("GLY"),
  QString("HIS"),
  QString("HOH"),
  QString("ILE"),
  QString("LEU"),
  QString("LYS"),
  QString("MET"),
  QString("PHE"),
  QString("PRO"),
  QString("SER"),
  QString("THR"),
  QString("TRP"),
  QString("TYR"),
  QString("VAL")
};

std::map<QString, QString> PredefinedElements::residueDefinitionsElement =
{
  {QString("ALA+C")    ,"C"},
  {QString("ALA+CA")   ,"C"},
  {QString("ALA+CB")   ,"C"},
  {QString("ALA+N")    ,"N"},
  {QString("ALA+O")    ,"O"},
  {QString("ALA+OXT")  ,"O"},
  {QString("ALA+H")    ,"H"},
  {QString("ALA+HA")   ,"H"},
  {QString("ALA+HB1")  ,"H"},
  {QString("ALA+HB2")  ,"H"},
  {QString("ALA+HB3")  ,"H"},

  {QString("ARG+C")    ,"C"},
  {QString("ARG+CA")   ,"C"},
  {QString("ARG+CB")   ,"C"},
  {QString("ARG+CD")   ,"C"},
  {QString("ARG+CG")   ,"C"},
  {QString("ARG+CZ")   ,"C"},
  {QString("ARG+N")    ,"N"},
  {QString("ARG+NE")   ,"N"},
  {QString("ARG+NH1")  ,"N"},
  {QString("ARG+NH2")  ,"N"},
  {QString("ARG+O")    ,"O"},
  {QString("ARG+OXT")  ,"O"},
  {QString("ARG+H")    ,"H"},
  {QString("ARG+HA")   ,"H"},
  {QString("ARG+HB2")  ,"H"},
  {QString("ARG+HB3")  ,"H"},
  {QString("ARG+HD2")  ,"H"},
  {QString("ARG+HD3")  ,"H"},
  {QString("ARG+HE")   ,"H"},
  {QString("ARG+HG2")  ,"H"},
  {QString("ARG+HG3")  ,"H"},
  {QString("ARG+HH11") ,"H"},
  {QString("ARG+HH12") ,"H"},
  {QString("ARG+HH21") ,"H"},
  {QString("ARG+HH22") ,"H"},

  {QString("ASN+C")    ,"C"},
  {QString("ASN+CA")   ,"C"},
  {QString("ASN+CB")   ,"C"},
  {QString("ASN+CG")   ,"C"},
  {QString("ASN+N")    ,"N"},
  {QString("ASN+ND2")  ,"N"},
  {QString("ASN+O")    ,"O"},
  {QString("ASN+OD1")  ,"O"},
  {QString("ASN+OXT")  ,"O"},
  {QString("ASN+H")    ,"H"},
  {QString("ASN+HA")   ,"H"},
  {QString("ASN+HB2")  ,"H"},
  {QString("ASN+HB3")  ,"H"},
  {QString("ASN+HD21") ,"H"},
  {QString("ASN+HD22") ,"H"},

  {QString("ASP+C")    ,"C"},
  {QString("ASP+CA")   ,"C"},
  {QString("ASP+CB")   ,"C"},
  {QString("ASP+CG")   ,"C"},
  {QString("ASP+N")    ,"N"},
  {QString("ASP+O")    ,"O"},
  {QString("ASP+OD1")  ,"O"},
  {QString("ASP+OD2")  ,"O"},
  {QString("ASP+OXT")  ,"O"},
  {QString("ASP+H")    ,"H"},
  {QString("ASP+HA")   ,"H"},
  {QString("ASP+HB2")  ,"H"},
  {QString("ASP+HB3")  ,"H"},

  {QString("CYS+C")    ,"C"},
  {QString("CYS+CA")   ,"C"},
  {QString("CYS+CB")   ,"C"},
  {QString("CYS+N")    ,"N"},
  {QString("CYS+O")    ,"O"},
  {QString("CYS+SG")   ,"S"},
  {QString("CYS+OXT")  ,"O"},
  {QString("CYS+H")    ,"H"},
  {QString("CYS+HA")   ,"H"},
  {QString("CYS+HB2")  ,"H"},
  {QString("CYS+HB3")  ,"H"},

  {QString("GLN+C")    ,"C"},
  {QString("GLN+CA")   ,"C"},
  {QString("GLN+CB")   ,"C"},
  {QString("GLN+CD")   ,"C"},
  {QString("GLN+CG")   ,"C"},
  {QString("GLN+N")    ,"N"},
  {QString("GLN+NE2")  ,"N"},
  {QString("GLN+O")    ,"O"},
  {QString("GLN+OE1")  ,"O"},
  {QString("GLN+OXT")  ,"O"},
  {QString("GLN+H")    ,"H"},
  {QString("GLN+HA")   ,"H"},
  {QString("GLN+HB2")  ,"H"},
  {QString("GLN+HB3")  ,"H"},
  {QString("GLN+HG2")  ,"H"},
  {QString("GLN+HG3")  ,"H"},
  {QString("GLN+HE21") ,"H"},
  {QString("GLN+HE22") ,"H"},

  {QString("GLU+C")    ,"C"},
  {QString("GLU+CA")   ,"C"},
  {QString("GLU+CB")   ,"C"},
  {QString("GLU+CD")   ,"C"},
  {QString("GLU+CG")   ,"C"},
  {QString("GLU+N")    ,"N"},
  {QString("GLU+O")    ,"O"},
  {QString("GLU+OE1")  ,"O"},
  {QString("GLU+OE2")  ,"O"},
  {QString("GLU+OXT")  ,"O"},
  {QString("GLU+H")    ,"H"},
  {QString("GLU+HA")   ,"H"},
  {QString("GLU+HB2")  ,"H"},
  {QString("GLU+HB3")  ,"H"},
  {QString("GLU+HG2")  ,"H"},
  {QString("GLU+HG3")  ,"H"},

  {QString("GLY+C")    ,"C"},
  {QString("GLY+CA")   ,"C"},
  {QString("GLY+N")    ,"N"},
  {QString("GLY+O")    ,"O"},
  {QString("GLY+OXT")  ,"O"},
  {QString("GLY+H")    ,"H"},
  {QString("GLY+HA")   ,"H"},
  {QString("GLY+HA2")  ,"H"},
  {QString("GLY+HA3")  ,"H"},
  {QString("GLY+HB2")  ,"H"},
  {QString("GLY+HB3")  ,"H"},
  {QString("GLY+HG2")  ,"H"},
  {QString("GLY+HG3")  ,"H"},

  {QString("HIS+C")    ,"C"},
  {QString("HIS+CA")   ,"C"},
  {QString("HIS+CB")   ,"C"},
  {QString("HIS+CD2")  ,"C"},
  {QString("HIS+CE1")  ,"C"},
  {QString("HIS+CG")   ,"C"},
  {QString("HIS+N")    ,"N"},
  {QString("HIS+ND1")  ,"N"},
  {QString("HIS+NE2")  ,"N"},
  {QString("HIS+O")    ,"O"},
  {QString("HIS+OXT")  ,"O"},
  {QString("HIS+H")    ,"H"},
  {QString("HIS+HA")   ,"H"},
  {QString("HIS+HB2")  ,"H"},
  {QString("HIS+HB3")  ,"H"},
  {QString("HIS+HD1")  ,"H"},
  {QString("HIS+HD2")  ,"H"},
  {QString("HIS+HE1")  ,"H"},

  {QString("HOH+O")    ,"C"},
  {QString("HOH+H")    ,"H"},

  {QString("ILE+C")    ,"C"},
  {QString("ILE+CA")   ,"C"},
  {QString("ILE+CB")   ,"C"},
  {QString("ILE+CD1")  ,"C"},
  {QString("ILE+CG1")  ,"C"},
  {QString("ILE+CG2")  ,"C"},
  {QString("ILE+N")    ,"N"},
  {QString("ILE+O")    ,"O"},
  {QString("ILE+OXT")  ,"O"},
  {QString("ILE+H")    ,"H"},
  {QString("ILE+HA")   ,"H"},
  {QString("ILE+HB")   ,"H"},
  {QString("ILE+HG12") ,"H"},
  {QString("ILE+HG13") ,"H"},
  {QString("ILE+HG21") ,"H"},
  {QString("ILE+HG22") ,"H"},
  {QString("ILE+HG23") ,"H"},
  {QString("ILE+HD11") ,"H"},
  {QString("ILE+HD12") ,"H"},
  {QString("ILE+HD13") ,"H"},

  {QString("LEU+C")    ,"C"},
  {QString("LEU+CA")   ,"C"},
  {QString("LEU+CB")   ,"C"},
  {QString("LEU+CD1")  ,"C"},
  {QString("LEU+CD2")  ,"C"},
  {QString("LEU+CG")   ,"C"},
  {QString("LEU+N")    ,"N"},
  {QString("LEU+O")    ,"O"},
  {QString("LEU+H")    ,"H"},
  {QString("LEU+HA")   ,"H"},
  {QString("LEU+HB2")  ,"H"},
  {QString("LEU+HB3")  ,"H"},
  {QString("LEU+HD11") ,"H"},
  {QString("LEU+HD12") ,"H"},
  {QString("LEU+HD13") ,"H"},
  {QString("LEU+HD21") ,"H"},
  {QString("LEU+HD22") ,"H"},
  {QString("LEU+HD23") ,"H"},
  {QString("LEU+HG")   ,"H"},

  {QString("LYS+C")    ,"C"},
  {QString("LYS+CA")   ,"C"},
  {QString("LYS+CB")   ,"C"},
  {QString("LYS+CD")   ,"C"},
  {QString("LYS+CE")   ,"C"},
  {QString("LYS+CG")   ,"C"},
  {QString("LYS+N")    ,"N"},
  {QString("LYS+NZ")   ,"N"},
  {QString("LYS+O")    ,"O"},
  {QString("LYS+OXT")  ,"O"},
  {QString("LYS+H")    ,"H"},
  {QString("LYS+HA")   ,"H"},
  {QString("LYS+HB2")  ,"H"},
  {QString("LYS+HB3")  ,"H"},
  {QString("LYS+HG2")  ,"H"},
  {QString("LYS+HG3")  ,"H"},
  {QString("LYS+HD2")  ,"H"},
  {QString("LYS+HD3")  ,"H"},
  {QString("LYS+HE2")  ,"H"},
  {QString("LYS+HE3")  ,"H"},

  {QString("MET+C")    ,"C"},
  {QString("MET+CA")   ,"C"},
  {QString("MET+CB")   ,"C"},
  {QString("MET+CE")   ,"C"},
  {QString("MET+CG")   ,"C"},
  {QString("MET+N")    ,"N"},
  {QString("MET+O")    ,"O"},
  {QString("MET+SD")   ,"S"},
  {QString("MET+OXT")  ,"O"},
  {QString("MET+H")    ,"H"},

  {QString("PHE+C")    ,"C"},
  {QString("PHE+CA")   ,"C"},
  {QString("PHE+CB")   ,"C"},
  {QString("PHE+CD1")  ,"C"},
  {QString("PHE+CD2")  ,"C"},
  {QString("PHE+CE1")  ,"C"},
  {QString("PHE+CE2")  ,"C"},
  {QString("PHE+CG")   ,"C"},
  {QString("PHE+CZ")   ,"C"},
  {QString("PHE+N")    ,"N"},
  {QString("PHE+O")    ,"O"},
  {QString("PHE+OXT")  ,"O"},
  {QString("PHE+H")    ,"H"},
  {QString("PHE+HA")   ,"H"},
  {QString("PHE+HB2")  ,"H"},
  {QString("PHE+HB3")  ,"H"},
  {QString("PHE+HD1")  ,"H"},
  {QString("PHE+HD2")  ,"H"},
  {QString("PHE+HE1")  ,"H"},
  {QString("PHE+HE2")  ,"H"},
  {QString("PHE+HZ")   ,"H"},

  {QString("PRO+C")    ,"C"},
  {QString("PRO+CA")   ,"C"},
  {QString("PRO+CB")   ,"C"},
  {QString("PRO+CD")   ,"C"},
  {QString("PRO+CG")   ,"C"},
  {QString("PRO+N")    ,"N"},
  {QString("PRO+O")    ,"O"},
  {QString("PRO+OXT")  ,"O"},
  {QString("PRO+H")    ,"H"},
  {QString("PRO+HA")   ,"H"},
  {QString("PRO+HB2")  ,"H"},
  {QString("PRO+HB3")  ,"H"},
  {QString("PRO+HD2")  ,"H"},
  {QString("PRO+HD3")  ,"H"},
  {QString("PRO+HG2")  ,"H"},
  {QString("PRO+HG3")  ,"H"},

  {QString("SER+C")    ,"C"},
  {QString("SER+CA")   ,"C"},
  {QString("SER+CB")   ,"C"},
  {QString("SER+N")    ,"N"},
  {QString("SER+O")    ,"O"},
  {QString("SER+OG")   ,"O"},
  {QString("SER+OXT")  ,"O"},
  {QString("SER+H")    ,"H"},
  {QString("SER+HA")   ,"H"},
  {QString("SER+HB2")  ,"H"},
  {QString("SER+HB3")  ,"H"},

  {QString("THR+C")    ,"C"},
  {QString("THR+CA")   ,"C"},
  {QString("THR+CB")   ,"C"},
  {QString("THR+CG2")  ,"C"},
  {QString("THR+N")    ,"N"},
  {QString("THR+O")    ,"O"},
  {QString("THR+OG1")  ,"O"},
  {QString("THR+OXT")  ,"O"},
  {QString("THR+H")    ,"H"},
  {QString("THR+HA")   ,"H"},
  {QString("THR+HB")   ,"H"},
  {QString("THR+HG1")  ,"H"},
  {QString("THR+HG21") ,"H"},
  {QString("THR+HG22") ,"H"},
  {QString("THR+HG23") ,"H"},
  {QString("THR+HH2")  ,"H"},

  {QString("TRP+C")    ,"C"},
  {QString("TRP+CA")   ,"C"},
  {QString("TRP+CB")   ,"C"},
  {QString("TRP+CD1")  ,"C"},
  {QString("TRP+CD2")  ,"C"},
  {QString("TRP+CE2")  ,"C"},
  {QString("TRP+CE3")  ,"C"},
  {QString("TRP+CG")   ,"C"},
  {QString("TRP+CH2")  ,"C"},
  {QString("TRP+CZ2")  ,"C"},
  {QString("TRP+CZ3")  ,"C"},
  {QString("TRP+N")    ,"N"},
  {QString("TRP+NE1")  ,"N"},
  {QString("TRP+O")    ,"O"},
  {QString("TRP+OXT")  ,"O"},
  {QString("TRP+H")    ,"H"},
  {QString("TRP+HA")   ,"H"},
  {QString("TRP+HB2")  ,"H"},
  {QString("TRP+HB3")  ,"H"},
  {QString("TRP+HD1")  ,"H"},
  {QString("TRP+HE1")  ,"H"},
  {QString("TRP+HE3")  ,"H"},
  {QString("TRP+HZ2")  ,"H"},
  {QString("TRP+HZ3")  ,"H"},
  {QString("TRP+HH2")  ,"H"},

  {QString("TYR+C")    ,"C"},
  {QString("TYR+CA")   ,"C"},
  {QString("TYR+CB")   ,"C"},
  {QString("TYR+CD1")  ,"C"},
  {QString("TYR+CD2")  ,"C"},
  {QString("TYR+CE1")  ,"C"},
  {QString("TYR+CE2")  ,"C"},
  {QString("TYR+CG")   ,"C"},
  {QString("TYR+CZ")   ,"C"},
  {QString("TYR+N")    ,"N"},
  {QString("TYR+O")    ,"O"},
  {QString("TYR+OH")   ,"O"},
  {QString("TYR+OXT")  ,"O"},
  {QString("TYR+H")    ,"H"},
  {QString("TYR+HA")   ,"H"},
  {QString("TYR+HB2")  ,"H"},
  {QString("TYR+HB3")  ,"H"},
  {QString("TYR+HD1")  ,"H"},
  {QString("TYR+HD2")  ,"H"},
  {QString("TYR+HE1")  ,"H"},
  {QString("TYR+HE2")  ,"H"},

  {QString("VAL+C")    ,"C"},
  {QString("VAL+CA")   ,"C"},
  {QString("VAL+CB")   ,"C"},
  {QString("VAL+CG1")  ,"C"},
  {QString("VAL+CG2")  ,"C"},
  {QString("VAL+N")    ,"N"},
  {QString("VAL+O")    ,"O"},
  {QString("VAL+OXT")  ,"O"},
  {QString("VAL+H")    ,"H"},
  {QString("VAL+HA")   ,"H"},
  {QString("VAL+HB")   ,"H"},
  {QString("VAL+HG11") ,"H"},
  {QString("VAL+HG12") ,"H"},
  {QString("VAL+HG13") ,"H"},
  {QString("VAL+HG21") ,"H"},
  {QString("VAL+HG22") ,"H"},
  {QString("VAL+HG23") ,"H"}
};

std::map<QString, QString> PredefinedElements::residueDefinitionsType =
{
  {QString("ALA+C")    ,"C"},
  {QString("ALA+CA")   ,"CH1E"},
  {QString("ALA+CB")   ,"CH3E"},
  {QString("ALA+N")    ,"NH1"},
  {QString("ALA+O")    ,"O"},
  {QString("ALA+OXT")  ,"O"},
  {QString("ALA+H")    ,"H"},
  {QString("ALA+HA")   ,"H"},
  {QString("ALA+HB1")  ,"H"},
  {QString("ALA+HB2")  ,"H"},
  {QString("ALA+HB3")  ,"H"},

  {QString("ARG+C")    ,"C"},
  {QString("ARG+CA")   ,"CH1E"},
  {QString("ARG+CB")   ,"CH2E"},
  {QString("ARG+CD")   ,"CH2E"},
  {QString("ARG+CG")   ,"CH2E"},
  {QString("ARG+CZ")   ,"CH0"},
  {QString("ARG+N")    ,"NH1"},
  {QString("ARG+NE")   ,"NH1S"},
  {QString("ARG+NH1")  ,"NC2"},
  {QString("ARG+NH2")  ,"NC2"},
  {QString("ARG+O")    ,"O"},
  {QString("ARG+OXT")  ,"O"},
  {QString("ARG+H")    ,"H"},
  {QString("ARG+HA")   ,"H"},
  {QString("ARG+HB2")  ,"H"},
  {QString("ARG+HB3")  ,"H"},
  {QString("ARG+HD2")  ,"H"},
  {QString("ARG+HD3")  ,"H"},
  {QString("ARG+HE")   ,"H"},
  {QString("ARG+HG2")  ,"H"},
  {QString("ARG+HG3")  ,"H"},
  {QString("ARG+HH11") ,"H"},
  {QString("ARG+HH12") ,"H"},
  {QString("ARG+HH21") ,"H"},
  {QString("ARG+HH22") ,"H"},

  {QString("ASN+C")    ,"C"},
  {QString("ASN+CA")   ,"CH1E"},
  {QString("ASN+CB")   ,"CH2E"},
  {QString("ASN+CG")   ,"CH0"},
  {QString("ASN+N")    ,"NH1"},
  {QString("ASN+ND2")  ,"NH2"},
  {QString("ASN+O")    ,"O"},
  {QString("ASN+OD1")  ,"OS"},
  {QString("ASN+OXT")  ,"O"},
  {QString("ASN+H")    ,"H"},
  {QString("ASN+HA")   ,"H"},
  {QString("ASN+HB2")  ,"H"},
  {QString("ASN+HB3")  ,"H"},
  {QString("ASN+HD21") ,"H"},
  {QString("ASN+HD22") ,"H"},

  {QString("ASP+C")    ,"C"},
  {QString("ASP+CA")   ,"CH1E"},
  {QString("ASP+CB")   ,"CH2E"},
  {QString("ASP+CG")   ,"CH0"},
  {QString("ASP+N")    ,"NH1"},
  {QString("ASP+O")    ,"O"},
  {QString("ASP+OD1")  ,"OC"},
  {QString("ASP+OD2")  ,"OC"},
  {QString("ASP+OXT")  ,"O"},
  {QString("ASP+H")    ,"H"},
  {QString("ASP+HA")   ,"H"},
  {QString("ASP+HB2")  ,"H"},
  {QString("ASP+HB3")  ,"H"},

  {QString("CYS+C")    ,"C"},
  {QString("CYS+CA")   ,"CH1E"},
  {QString("CYS+CB")   ,"CH2E"},
  {QString("CYS+N")    ,"NH1"},
  {QString("CYS+O")    ,"O"},
  {QString("CYS+SG")   ,"SH1E"},
  {QString("CYS+OXT")  ,"O"},
  {QString("CYS+H")    ,"H"},
  {QString("CYS+HA")   ,"H"},
  {QString("CYS+HB2")  ,"H"},
  {QString("CYS+HB3")  ,"H"},

  {QString("GLN+C")    ,"C"},
  {QString("GLN+CA")   ,"CH1E"},
  {QString("GLN+CB")   ,"CH2E"},
  {QString("GLN+CD")   ,"CH0"},
  {QString("GLN+CG")   ,"CH2E"},
  {QString("GLN+N")    ,"NH1"},
  {QString("GLN+NE2")  ,"NH2"},
  {QString("GLN+O")    ,"O"},
  {QString("GLN+OE1")  ,"OS"},
  {QString("GLN+OXT")  ,"O"},
  {QString("GLN+H")    ,"H"},
  {QString("GLN+HA")   ,"H"},
  {QString("GLN+HB2")  ,"H"},
  {QString("GLN+HB3")  ,"H"},
  {QString("GLN+HG2")  ,"H"},
  {QString("GLN+HG3")  ,"H"},
  {QString("GLN+HE21") ,"H"},
  {QString("GLN+HE22") ,"H"},

  {QString("GLU+C")    ,"C"},
  {QString("GLU+CA")   ,"CH1E"},
  {QString("GLU+CB")   ,"CH2E"},
  {QString("GLU+CD")   ,"CH0"},
  {QString("GLU+CG")   ,"CH2E"},
  {QString("GLU+N")    ,"NH1"},
  {QString("GLU+O")    ,"O"},
  {QString("GLU+OE1")  ,"OC"},
  {QString("GLU+OE2")  ,"OC"},
  {QString("GLU+OXT")  ,"O"},
  {QString("GLU+H")    ,"H"},
  {QString("GLU+HA")   ,"H"},
  {QString("GLU+HB2")  ,"H"},
  {QString("GLU+HB3")  ,"H"},
  {QString("GLU+HG2")  ,"H"},
  {QString("GLU+HG3")  ,"H"},

  {QString("GLY+C")    ,"C"},
  {QString("GLY+CA")   ,"CH2G"},
  {QString("GLY+N")    ,"NH1"},
  {QString("GLY+O")    ,"O"},
  {QString("GLY+OXT")  ,"O"},
  {QString("GLY+H")    ,"H"},
  {QString("GLY+HA")   ,"H"},
  {QString("GLY+HA2")  ,"H"},
  {QString("GLY+HA3")  ,"H"},
  {QString("GLY+HB2")  ,"H"},
  {QString("GLY+HB3")  ,"H"},
  {QString("GLY+HG2")  ,"H"},
  {QString("GLY+HG3")  ,"H"},

  {QString("HIS+C")    ,"C"},
  {QString("HIS+CA")   ,"CH1E"},
  {QString("HIS+CB")   ,"CH2E"},
  {QString("HIS+CD2")  ,"CR1H"},
  {QString("HIS+CE1")  ,"CRHH"},
  {QString("HIS+CG")   ,"C5"},
  {QString("HIS+N")    ,"NH1"},
  {QString("HIS+ND1")  ,"NH1S"},
  {QString("HIS+NE2")  ,"NH1S"},
  {QString("HIS+O")    ,"O"},
  {QString("HIS+OXT")  ,"O"},
  {QString("HIS+H")    ,"H"},
  {QString("HIS+HA")   ,"H"},
  {QString("HIS+HB2")  ,"H"},
  {QString("HIS+HB3")  ,"H"},
  {QString("HIS+HD1")  ,"H"},
  {QString("HIS+HD2")  ,"H"},
  {QString("HIS+HE1")  ,"H"},

  {QString("HOH+O")    ,"HOH"},
  {QString("HOH+H")    ,"HOH"},

  {QString("ILE+C")    ,"C"},
  {QString("ILE+CA")   ,"CH1E"},
  {QString("ILE+CB")   ,"CH1S"},
  {QString("ILE+CD1")  ,"CH3E"},
  {QString("ILE+CG1")  ,"CH2E"},
  {QString("ILE+CG2")  ,"CH3E"},
  {QString("ILE+N")    ,"NH1"},
  {QString("ILE+O")    ,"O"},
  {QString("ILE+OXT")  ,"O"},
  {QString("ILE+H")    ,"H"},
  {QString("ILE+HA")   ,"H"},
  {QString("ILE+HB")   ,"H"},
  {QString("ILE+HG12") ,"H"},
  {QString("ILE+HG13") ,"H"},
  {QString("ILE+HG21") ,"H"},
  {QString("ILE+HG22") ,"H"},
  {QString("ILE+HG23") ,"H"},
  {QString("ILE+HD11") ,"H"},
  {QString("ILE+HD12") ,"H"},
  {QString("ILE+HD13") ,"H"},

  {QString("LEU+C")    ,"C"},
  {QString("LEU+CA")   ,"CH1E"},
  {QString("LEU+CB")   ,"CH2E"},
  {QString("LEU+CD1")  ,"CH3E"},
  {QString("LEU+CD2")  ,"CH3E"},
  {QString("LEU+CG")   ,"CH1S"},
  {QString("LEU+N")    ,"NH1"},
  {QString("LEU+O")    ,"O"},
  {QString("LEU+H")    ,"H"},
  {QString("LEU+HA")   ,"H"},
  {QString("LEU+HB2")  ,"H"},
  {QString("LEU+HB3")  ,"H"},
  {QString("LEU+HD11") ,"H"},
  {QString("LEU+HD12") ,"H"},
  {QString("LEU+HD13") ,"H"},
  {QString("LEU+HD21") ,"H"},
  {QString("LEU+HD22") ,"H"},
  {QString("LEU+HD23") ,"H"},
  {QString("LEU+HG")   ,"H"},

  {QString("LYS+C")    ,"C"},
  {QString("LYS+CA")   ,"CH1E"},
  {QString("LYS+CB")   ,"CH2E"},
  {QString("LYS+CD")   ,"CH2E"},
  {QString("LYS+CE")   ,"CH2E"},
  {QString("LYS+CG")   ,"CH2E"},
  {QString("LYS+N")    ,"NH1"},
  {QString("LYS+NZ")   ,"NH3"},
  {QString("LYS+O")    ,"O"},
  {QString("LYS+OXT")  ,"O"},
  {QString("LYS+H")    ,"H"},
  {QString("LYS+HA")   ,"H"},
  {QString("LYS+HB2")  ,"H"},
  {QString("LYS+HB3")  ,"H"},
  {QString("LYS+HG2")  ,"H"},
  {QString("LYS+HG3")  ,"H"},
  {QString("LYS+HD2")  ,"H"},
  {QString("LYS+HD3")  ,"H"},
  {QString("LYS+HE2")  ,"H"},
  {QString("LYS+HE3")  ,"H"},

  {QString("MET+C")    ,"C"},
  {QString("MET+CA")   ,"CH1E"},
  {QString("MET+CB")   ,"CH2E"},
  {QString("MET+CE")   ,"CH3E"},
  {QString("MET+CG")   ,"CH2E"},
  {QString("MET+N")    ,"NH1"},
  {QString("MET+O")    ,"O"},
  {QString("MET+SD")   ,"SM"},
  {QString("MET+OXT")  ,"O"},
  {QString("MET+H")    ,"H"},

  {QString("PHE+C")    ,"C"},
  {QString("PHE+CA")   ,"CH1E"},
  {QString("PHE+CB")   ,"CH2E"},
  {QString("PHE+CD1")  ,"CR1E"},
  {QString("PHE+CD2")  ,"CR1E"},
  {QString("PHE+CE1")  ,"CR1E"},
  {QString("PHE+CE2")  ,"CR1E"},
  {QString("PHE+CG")   ,"CF"},
  {QString("PHE+CZ")   ,"CR1E"},
  {QString("PHE+N")    ,"NH1"},
  {QString("PHE+O")    ,"O"},
  {QString("PHE+OXT")  ,"O"},
  {QString("PHE+H")    ,"H"},
  {QString("PHE+HA")   ,"H"},
  {QString("PHE+HB2")  ,"H"},
  {QString("PHE+HB3")  ,"H"},
  {QString("PHE+HD1")  ,"H"},
  {QString("PHE+HD2")  ,"H"},
  {QString("PHE+HE1")  ,"H"},
  {QString("PHE+HE2")  ,"H"},
  {QString("PHE+HZ")   ,"H"},

  {QString("PRO+C")    ,"C"},
  {QString("PRO+CA")   ,"CH1E"},
  {QString("PRO+CB")   ,"CH2E"},
  {QString("PRO+CD")   ,"CH2P"},
  {QString("PRO+CG")   ,"CH2P"},
  {QString("PRO+N")    ,"N"},
  {QString("PRO+O")    ,"O"},
  {QString("PRO+OXT")  ,"O"},
  {QString("PRO+H")    ,"H"},
  {QString("PRO+HA")   ,"H"},
  {QString("PRO+HB2")  ,"H"},
  {QString("PRO+HB3")  ,"H"},
  {QString("PRO+HD2")  ,"H"},
  {QString("PRO+HD3")  ,"H"},
  {QString("PRO+HG2")  ,"H"},
  {QString("PRO+HG3")  ,"H"},

  {QString("SER+C")    ,"C"},
  {QString("SER+CA")   ,"CH1E"},
  {QString("SER+CB")   ,"CH2E"},
  {QString("SER+N")    ,"NH1"},
  {QString("SER+O")    ,"O"},
  {QString("SER+OG")   ,"OH1"},
  {QString("SER+OXT")  ,"O"},
  {QString("SER+H")    ,"H"},
  {QString("SER+HA")   ,"H"},
  {QString("SER+HB2")  ,"H"},
  {QString("SER+HB3")  ,"H"},

  {QString("THR+C")    ,"C"},
  {QString("THR+CA")   ,"CH1E"},
  {QString("THR+CB")   ,"CH1S"},
  {QString("THR+CG2")  ,"CH3E"},
  {QString("THR+N")    ,"NH1"},
  {QString("THR+O")    ,"O"},
  {QString("THR+OG1")  ,"OH1"},
  {QString("THR+OXT")  ,"O"},
  {QString("THR+H")    ,"H"},
  {QString("THR+HA")   ,"H"},
  {QString("THR+HB")   ,"H"},
  {QString("THR+HG1")  ,"H"},
  {QString("THR+HG21") ,"H"},
  {QString("THR+HG22") ,"H"},
  {QString("THR+HG23") ,"H"},
  {QString("THR+HH2")  ,"H"},

  {QString("TRP+C")    ,"C"},
  {QString("TRP+CA")   ,"CH1E"},
  {QString("TRP+CB")   ,"CH2E"},
  {QString("TRP+CD1")  ,"CR1E"},
  {QString("TRP+CD2")  ,"CW"},
  {QString("TRP+CE2")  ,"CW"},
  {QString("TRP+CE3")  ,"CR1E"},
  {QString("TRP+CG")   ,"C5W"},
  {QString("TRP+CH2")  ,"CR1W"},
  {QString("TRP+CZ2")  ,"CR1W"},
  {QString("TRP+CZ3")  ,"CR1E"},
  {QString("TRP+N")    ,"NH1"},
  {QString("TRP+NE1")  ,"NH1S"},
  {QString("TRP+O")    ,"O"},
  {QString("TRP+OXT")  ,"O"},
  {QString("TRP+H")    ,"H"},
  {QString("TRP+HA")   ,"H"},
  {QString("TRP+HB2")  ,"H"},
  {QString("TRP+HB3")  ,"H"},
  {QString("TRP+HD1")  ,"H"},
  {QString("TRP+HE1")  ,"H"},
  {QString("TRP+HE3")  ,"H"},
  {QString("TRP+HZ2")  ,"H"},
  {QString("TRP+HZ3")  ,"H"},
  {QString("TRP+HH2")  ,"H"},

  {QString("TYR+C")    ,"C"},
  {QString("TYR+CA")   ,"CH1E"},
  {QString("TYR+CB")   ,"CH2E"},
  {QString("TYR+CD1")  ,"CR1E"},
  {QString("TYR+CD2")  ,"CR1E"},
  {QString("TYR+CE1")  ,"CR1E"},
  {QString("TYR+CE2")  ,"CR1E"},
  {QString("TYR+CG")   ,"CY"},
  {QString("TYR+CZ")   ,"CY2"},
  {QString("TYR+N")    ,"NH1"},
  {QString("TYR+O")    ,"O"},
  {QString("TYR+OH")   ,"OH1"},
  {QString("TYR+OXT")  ,"O"},
  {QString("TYR+H")    ,"H"},
  {QString("TYR+HA")   ,"H"},
  {QString("TYR+HB2")  ,"H"},
  {QString("TYR+HB3")  ,"H"},
  {QString("TYR+HD1")  ,"H"},
  {QString("TYR+HD2")  ,"H"},
  {QString("TYR+HE1")  ,"H"},
  {QString("TYR+HE2")  ,"H"},

  {QString("VAL+C")    ,"C"},
  {QString("VAL+CA")   ,"CH1E"},
  {QString("VAL+CB")   ,"CH1S"},
  {QString("VAL+CG1")  ,"CH3E"},
  {QString("VAL+CG2")  ,"CH3E"},
  {QString("VAL+N")    ,"NH1"},
  {QString("VAL+O")    ,"O"},
  {QString("VAL+OXT")  ,"O"},
  {QString("VAL+H")    ,"H"},
  {QString("VAL+HA")   ,"H"},
  {QString("VAL+HB")   ,"H"},
  {QString("VAL+HG11") ,"H"},
  {QString("VAL+HG12") ,"H"},
  {QString("VAL+HG13") ,"H"},
  {QString("VAL+HG21") ,"H"},
  {QString("VAL+HG22") ,"H"},
  {QString("VAL+HG23") ,"H"}
};

std::map<QString, std::vector<QString>> PredefinedElements::residueDefinitionsBondedAtoms =
{
  {QString("ALA+C")    ,{"CA","O"}},
  {QString("ALA+CA")   ,{"N","CB","C"}},
  {QString("ALA+CB")   ,{"CA"}},
  {QString("ALA+N")    ,{"-C","CA"}},
  {QString("ALA+O")    ,{"C"}},
  {QString("ALA+OXT")  ,{"C"}},
  {QString("ALA+H")    ,{}},
  {QString("ALA+HA")   ,{}},
  {QString("ALA+HB1")  ,{}},
  {QString("ALA+HB2")  ,{}},
  {QString("ALA+HB3")  ,{}},

  {QString("ARG+C")    ,{"CA","O"}},
  {QString("ARG+CA")   ,{"N ","CB ","C"}},
  {QString("ARG+CB")   ,{"CA","CG"}},
  {QString("ARG+CD")   ,{"CG","NE"}},
  {QString("ARG+CG")   ,{"CB","CD"}},
  {QString("ARG+CZ")   ,{"NE"," NH1","NH2"}},
  {QString("ARG+N")    ,{"-C","CA"}},
  {QString("ARG+NE")   ,{"CD","CZ"}},
  {QString("ARG+NH1")  ,{"CZ"}},
  {QString("ARG+NH2")  ,{"CZ"}},
  {QString("ARG+O")    ,{"C"}},
  {QString("ARG+OXT")  ,{"C"}},
  {QString("ARG+H")    ,{}},
  {QString("ARG+HA")   ,{}},
  {QString("ARG+HB2")  ,{}},
  {QString("ARG+HB3")  ,{}},
  {QString("ARG+HD2")  ,{}},
  {QString("ARG+HD3")  ,{}},
  {QString("ARG+HE")   ,{}},
  {QString("ARG+HG2")  ,{}},
  {QString("ARG+HG3")  ,{}},
  {QString("ARG+HH11") ,{}},
  {QString("ARG+HH12") ,{}},
  {QString("ARG+HH21") ,{}},
  {QString("ARG+HH22") ,{}},

  {QString("ASN+C")    ,{"CA","O"}},
  {QString("ASN+CA")   ,{"N","CB","C"}},
  {QString("ASN+CB")   ,{"CA","CG"}},
  {QString("ASN+CG")   ,{"CB","OD1","ND2"}},
  {QString("ASN+N")    ,{"-C","CA"}},
  {QString("ASN+ND2")  ,{"CG"}},
  {QString("ASN+O")    ,{"C"}},
  {QString("ASN+OD1")  ,{"CG"}},
  {QString("ASN+OXT")  ,{"C"}},
  {QString("ASN+H")    ,{}},
  {QString("ASN+HA")   ,{}},
  {QString("ASN+HB2")  ,{}},
  {QString("ASN+HB3")  ,{}},
  {QString("ASN+HD21") ,{}},
  {QString("ASN+HD22") ,{}},

  {QString("ASP+C")    ,{"CA","O"}},
  {QString("ASP+CA")   ,{"N ","CB","C"}},
  {QString("ASP+CB")   ,{"CA ","CG"}},
  {QString("ASP+CG")   ,{"CB ","OD1","OD2"}},
  {QString("ASP+N")    ,{"-C ","CA"}},
  {QString("ASP+O")    ,{"C"}},
  {QString("ASP+OD1")  ,{"CG"}},
  {QString("ASP+OD2")  ,{"CG"}},
  {QString("ASP+OXT")  ,{"C"}},
  {QString("ASP+H")    ,{}},
  {QString("ASP+HA")   ,{}},
  {QString("ASP+HB2")  ,{}},
  {QString("ASP+HB3")  ,{}},

  {QString("CYS+C")    ,{"CA","O"}},
  {QString("CYS+CA")   ,{"N","CB ","C"}},
  {QString("CYS+CB")   ,{"CA","SG"}},
  {QString("CYS+N")    ,{"-C","CA"}},
  {QString("CYS+O")    ,{"C"}},
  {QString("CYS+SG")   ,{"CB"}},
  {QString("CYS+OXT")  ,{"C"}},
  {QString("CYS+H")    ,{}},
  {QString("CYS+HA")   ,{}},
  {QString("CYS+HB2")  ,{}},
  {QString("CYS+HB3")  ,{}},

  {QString("GLN+C")    ,{"CA","O"}},
  {QString("GLN+CA")   ,{"N","CB","C"}},
  {QString("GLN+CB")   ,{"CA ","CG"}},
  {QString("GLN+CD")   ,{"CG","NE2","OE1"}},
  {QString("GLN+CG")   ,{"CB","CD"}},
  {QString("GLN+N")    ,{"-C ","CA"}},
  {QString("GLN+NE2")  ,{"CD"}},
  {QString("GLN+O")    ,{"C"}},
  {QString("GLN+OE1")  ,{"CD"}},
  {QString("GLN+OXT")  ,{"C"}},
  {QString("GLN+H")    ,{}},
  {QString("GLN+HA")   ,{}},
  {QString("GLN+HB2")  ,{}},
  {QString("GLN+HB3")  ,{}},
  {QString("GLN+HG2")  ,{}},
  {QString("GLN+HG3")  ,{}},
  {QString("GLN+HE21") ,{}},
  {QString("GLN+HE22") ,{}},

  {QString("GLU+C")    ,{"CA","O"}},
  {QString("GLU+CA")   ,{"N","CB","C"}},
  {QString("GLU+CB")   ,{"CA","CG"}},
  {QString("GLU+CD")   ,{"CG","OE1 ","OE2"}},
  {QString("GLU+CG")   ,{"CB ","CD"}},
  {QString("GLU+N")    ,{"-C","CA"}},
  {QString("GLU+O")    ,{"C"}},
  {QString("GLU+OE1")  ,{"CD"}},
  {QString("GLU+OE2")  ,{"CD"}},
  {QString("GLU+OXT")  ,{"C"}},
  {QString("GLU+H")    ,{}},
  {QString("GLU+HA")   ,{}},
  {QString("GLU+HB2")  ,{}},
  {QString("GLU+HB3")  ,{}},
  {QString("GLU+HG2")  ,{}},
  {QString("GLU+HG3")  ,{}},

  {QString("GLY+C")    ,{"CA","O"}},
  {QString("GLY+CA")   ,{"N","C"}},
  {QString("GLY+N")    ,{"-C","CA"}},
  {QString("GLY+O")    ,{"C"}},
  {QString("GLY+OXT")  ,{"C"}},
  {QString("GLY+H")    ,{}},
  {QString("GLY+HA")   ,{}},
  {QString("GLY+HA2")  ,{}},
  {QString("GLY+HA3")  ,{}},
  {QString("GLY+HB2")  ,{}},
  {QString("GLY+HB3")  ,{}},
  {QString("GLY+HG2")  ,{}},
  {QString("GLY+HG3")  ,{}},

  {QString("HIS+C")    ,{"CA","O"}},
  {QString("HIS+CA")   ,{"N","CB","C"}},
  {QString("HIS+CB")   ,{"CA","CG"}},
  {QString("HIS+CD2")  ,{"CG ","NE2"}},
  {QString("HIS+CE1")  ,{"ND1","NE2"}},
  {QString("HIS+CG")   ,{"CB","CD2","ND1"}},
  {QString("HIS+N")    ,{"-C","CA"}},
  {QString("HIS+ND1")  ,{"CG ","CE1"}},
  {QString("HIS+NE2")  ,{"CD2","CE1"}},
  {QString("HIS+O")    ,{"C"}},
  {QString("HIS+OXT")  ,{"C"}},
  {QString("HIS+H")    ,{}},
  {QString("HIS+HA")   ,{}},
  {QString("HIS+HB2")  ,{}},
  {QString("HIS+HB3")  ,{}},
  {QString("HIS+HD1")  ,{}},
  {QString("HIS+HD2")  ,{}},
  {QString("HIS+HE1")  ,{}},

  {QString("HOH+O")    ,{}},
  {QString("HOH+H")    ,{}},

  {QString("ILE+C")    ,{"CA","O"}},
  {QString("ILE+CA")   ,{"N ","CB ","C"}},
  {QString("ILE+CB")   ,{"CA","CG1","CG2"}},
  {QString("ILE+CD1")  ,{"CG1"}},
  {QString("ILE+CG1")  ,{"CB ","CD1"}},
  {QString("ILE+CG2")  ,{"CB"}},
  {QString("ILE+N")    ,{"-C","CA"}},
  {QString("ILE+O")    ,{"C"}},
  {QString("ILE+OXT")  ,{"C"}},
  {QString("ILE+H")    ,{}},
  {QString("ILE+HA")   ,{}},
  {QString("ILE+HB")   ,{}},
  {QString("ILE+HG12") ,{}},
  {QString("ILE+HG13") ,{}},
  {QString("ILE+HG21") ,{}},
  {QString("ILE+HG22") ,{}},
  {QString("ILE+HG23") ,{}},
  {QString("ILE+HD11") ,{}},
  {QString("ILE+HD12") ,{}},
  {QString("ILE+HD13") ,{}},

  {QString("LEU+C")    ,{"CA","O"}},
  {QString("LEU+CA")   ,{"N ","CB","C"}},
  {QString("LEU+CB")   ,{"CA ","CG"}},
  {QString("LEU+CD1")  ,{"CG"}},
  {QString("LEU+CD2")  ,{"CG"}},
  {QString("LEU+CG")   ,{"CB ","CD1","CD2"}},
  {QString("LEU+N")    ,{"-C ","CA"}},
  {QString("LEU+O")    ,{"C"}},
  {QString("LEU+H")    ,{}},
  {QString("LEU+HA")   ,{}},
  {QString("LEU+HB2")  ,{}},
  {QString("LEU+HB3")  ,{}},
  {QString("LEU+HD11") ,{}},
  {QString("LEU+HD12") ,{}},
  {QString("LEU+HD13") ,{}},
  {QString("LEU+HD21") ,{}},
  {QString("LEU+HD22") ,{}},
  {QString("LEU+HD23") ,{}},
  {QString("LEU+HG")   ,{}},

  {QString("LYS+C")    ,{"CA ","O"}},
  {QString("LYS+CA")   ,{"N ","CB","C"}},
  {QString("LYS+CB")   ,{"CA ","CG"}},
  {QString("LYS+CD")   ,{"CG ","CE"}},
  {QString("LYS+CE")   ,{"CD ","NZ"}},
  {QString("LYS+CG")   ,{"CB ","CD"}},
  {QString("LYS+N")    ,{"-C  ","CA"}},
  {QString("LYS+NZ")   ,{"CE"}},
  {QString("LYS+O")    ,{"C"}},
  {QString("LYS+OXT")  ,{"C"}},
  {QString("LYS+H")    ,{}},
  {QString("LYS+HA")   ,{}},
  {QString("LYS+HB2")  ,{}},
  {QString("LYS+HB3")  ,{}},
  {QString("LYS+HG2")  ,{}},
  {QString("LYS+HG3")  ,{}},
  {QString("LYS+HD2")  ,{}},
  {QString("LYS+HD3")  ,{}},
  {QString("LYS+HE2")  ,{}},
  {QString("LYS+HE3")  ,{}},

  {QString("MET+C")    ,{"CA ","O"}},
  {QString("MET+CA")   ,{"N","CB","C"}},
  {QString("MET+CB")   ,{"CA ","CG"}},
  {QString("MET+CE")   ,{"SD"}},
  {QString("MET+CG")   ,{"CB ","SD"}},
  {QString("MET+N")    ,{"-C","CA"}},
  {QString("MET+O")    ,{"C"}},
  {QString("MET+SD")   ,{"CG ","CE"}},
  {QString("MET+OXT")  ,{"C"}},
  {QString("MET+H")    ,{}},

  {QString("PHE+C")    ,{"CA","O"}},
  {QString("PHE+CA")   ,{"N","CB","C"}},
  {QString("PHE+CB")   ,{"CA","CG"}},
  {QString("PHE+CD1")  ,{"CG ","CE1"}},
  {QString("PHE+CD2")  ,{"CG ","CE2"}},
  {QString("PHE+CE1")  ,{"CD1","CZ"}},
  {QString("PHE+CE2")  ,{"CD2 ","CZ"}},
  {QString("PHE+CG")   ,{"CB ","CD1","CD2"}},
  {QString("PHE+CZ")   ,{"CE1","CE2"}},
  {QString("PHE+N")    ,{"-C ","CA"}},
  {QString("PHE+O")    ,{"C"}},
  {QString("PHE+OXT")  ,{"C"}},
  {QString("PHE+H")    ,{}},
  {QString("PHE+HA")   ,{}},
  {QString("PHE+HB2")  ,{}},
  {QString("PHE+HB3")  ,{}},
  {QString("PHE+HD1")  ,{}},
  {QString("PHE+HD2")  ,{}},
  {QString("PHE+HE1")  ,{}},
  {QString("PHE+HE2")  ,{}},
  {QString("PHE+HZ")   ,{}},

  {QString("PRO+C")    ,{"CA","O"}},
  {QString("PRO+CA")   ,{"N","CB","C"}},
  {QString("PRO+CB")   ,{"CA","CG"}},
  {QString("PRO+CD")   ,{"N","CG"}},
  {QString("PRO+CG")   ,{"CB","CD"}},
  {QString("PRO+N")    ,{"-C","CA","CD"}},
  {QString("PRO+O")    ,{"C"}},
  {QString("PRO+OXT")  ,{"C"}},
  {QString("PRO+H")    ,{}},
  {QString("PRO+HA")   ,{}},
  {QString("PRO+HB2")  ,{}},
  {QString("PRO+HB3")  ,{}},
  {QString("PRO+HD2")  ,{}},
  {QString("PRO+HD3")  ,{}},
  {QString("PRO+HG2")  ,{}},
  {QString("PRO+HG3")  ,{}},

  {QString("SER+C")    ,{"CA","O"}},
  {QString("SER+CA")   ,{"N","CB","C"}},
  {QString("SER+CB")   ,{"CA","OG"}},
  {QString("SER+N")    ,{"-C","CA"}},
  {QString("SER+O")    ,{"C"}},
  {QString("SER+OG")   ,{"CB"}},
  {QString("SER+OXT")  ,{"C"}},
  {QString("SER+H")    ,{}},
  {QString("SER+HA")   ,{}},
  {QString("SER+HB2")  ,{}},
  {QString("SER+HB3")  ,{}},

  {QString("THR+C")    ,{"CA","O"}},
  {QString("THR+CA")   ,{"N","CB","C"}},
  {QString("THR+CB")   ,{"CA","CG2","OG1"}},
  {QString("THR+CG2")  ,{"CB"}},
  {QString("THR+N")    ,{"-C","CA"}},
  {QString("THR+O")    ,{"C"}},
  {QString("THR+OG1")  ,{"CB"}},
  {QString("THR+OXT")  ,{"C"}},
  {QString("THR+H")    ,{}},
  {QString("THR+HA")   ,{}},
  {QString("THR+HB")   ,{}},
  {QString("THR+HG1")  ,{}},
  {QString("THR+HG21") ,{}},
  {QString("THR+HG22") ,{}},
  {QString("THR+HG23") ,{}},
  {QString("THR+HH2")  ,{}},

  {QString("TRP+C")    ,{"CA","O"}},
  {QString("TRP+CA")   ,{"N ","CB","C"}},
  {QString("TRP+CB")   ,{"CA","CG"}},
  {QString("TRP+CD1")  ,{"CG ","NE1"}},
  {QString("TRP+CD2")  ,{"CG "," CE2","CE3"}},
  {QString("TRP+CE2")  ,{"CD2 ","CZ2","NE1"}},
  {QString("TRP+CE3")  ,{"CD2","CZ3"}},
  {QString("TRP+CG")   ,{"CB ","CD1","CD2"}},
  {QString("TRP+CH2")  ,{"CZ2","CZ3"}},
  {QString("TRP+CZ2")  ,{"CE2","CH2"}},
  {QString("TRP+CZ3")  ,{"CE3","CH2"}},
  {QString("TRP+N")    ,{"-C","CA"}},
  {QString("TRP+NE1")  ,{"CD1 ","CE2"}},
  {QString("TRP+O")    ,{"C"}},
  {QString("TRP+OXT")  ,{"C"}},
  {QString("TRP+H")    ,{}},
  {QString("TRP+HA")   ,{}},
  {QString("TRP+HB2")  ,{}},
  {QString("TRP+HB3")  ,{}},
  {QString("TRP+HD1")  ,{}},
  {QString("TRP+HE1")  ,{}},
  {QString("TRP+HE3")  ,{}},
  {QString("TRP+HZ2")  ,{}},
  {QString("TRP+HZ3")  ,{}},
  {QString("TRP+HH2")  ,{}},

  {QString("TYR+C")    ,{"CA","O"}},
  {QString("TYR+CA")   ,{"N","CB","C"}},
  {QString("TYR+CB")   ,{"CA","CG"}},
  {QString("TYR+CD1")  ,{"CG","CE1"}},
  {QString("TYR+CD2")  ,{"CG","CE2"}},
  {QString("TYR+CE1")  ,{"CD1","CZ"}},
  {QString("TYR+CE2")  ,{"CD2","CZ"}},
  {QString("TYR+CG")   ,{"CB","CD1","CD2"}},
  {QString("TYR+CZ")   ,{"CE1","CE2","OH"}},
  {QString("TYR+N")    ,{"-C","CA"}},
  {QString("TYR+O")    ,{"C"}},
  {QString("TYR+OH")   ,{"CZ"}},
  {QString("TYR+OXT")  ,{"C"}},
  {QString("TYR+H")    ,{}},
  {QString("TYR+HA")   ,{}},
  {QString("TYR+HB2")  ,{}},
  {QString("TYR+HB3")  ,{}},
  {QString("TYR+HD1")  ,{}},
  {QString("TYR+HD2")  ,{}},
  {QString("TYR+HE1")  ,{}},
  {QString("TYR+HE2")  ,{}},

  {QString("VAL+C")    ,{"CA","O"}},
  {QString("VAL+CA")   ,{"N","CB","C"}},
  {QString("VAL+CB")   ,{"CA","CG1","CG2"}},
  {QString("VAL+CG1")  ,{"CB"}},
  {QString("VAL+CG2")  ,{"CB"}},
  {QString("VAL+N")    ,{"-C","CA"}},
  {QString("VAL+O")    ,{"C"}},
  {QString("VAL+OXT")  ,{"C"}},
  {QString("VAL+H")    ,{}},
  {QString("VAL+HA")   ,{}},
  {QString("VAL+HB")   ,{}},
  {QString("VAL+HG11") ,{}},
  {QString("VAL+HG12") ,{}},
  {QString("VAL+HG13") ,{}},
  {QString("VAL+HG21") ,{}},
  {QString("VAL+HG22") ,{}},
  {QString("VAL+HG23") ,{}}
};
